version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-nest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_microservice
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
  nestjs:
    build: .
    container_name: nestjs-app
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: 'mysql://nestuser:nestpass@mysql:3306/nest_microservice'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

volumes:
  mysql_data:
